force-app/main/default/objects/Ingreso__c/Ingreso__c.object-meta.xml
<CustomObject>
    <label>Ingreso</label>
    <nameField>
        <label>Ingreso Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ingresos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ingreso__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <label>Mes</label>
    <referenceTo>Mes__c</referenceTo>
    <relationshipLabel>Ingresos</relationshipLabel>
    <relationshipName>Ingresos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mes__c/Mes__c.object-meta.xml
<CustomObject>
   
    <label>Mes</label>
    <nameField>
        <label>Mes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_AfterUpdateIngreso.cls
@isTest
public with sharing class Test_AfterUpdateIngreso {



    @isTest
    public static void given_MesesWithIngresos_WhenCalling_getAllMesesFromIngresos_Expected_SetWithMeses() 
    {
        Ingreso__c ingreso1 = new Ingreso__c( Mes__C = TestUtility.getFakeId(Ingreso__c.getSObjectType(), '0' ) );

        AfterUpdateIngresoTriggerHandler handler = new AfterUpdateIngresoTriggerHandler( new Ingreso__c[]
        {
            ingreso1
        });
        
        Test.startTest();
        handler.getAllMesesFromIngresos();
        Test.stopTest();

        System.assertEquals(1, handler.meses.size());
    }
    
    @isTest
    public static void given_AMesWithIngresos_When_UpdateOneIngreso_Expected_GastoDiezmoMontoUpdated() 
    {
        

    }
}