force-app/main/default/objects/Gasto__c/Gasto__c.object-meta.xml
<CustomObject>
    <label>Gasto</label>
    <nameField>
        <displayFormat>G - {0000}</displayFormat>
        <label>Gasto Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gastos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gasto__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diezmo</fullName>
                <default>true</default>
                <label>Diezmo</label>
            </value>
            <value>
                <fullName>Transporte</fullName>
            </value>
            <value>
                <fullName>Entretenimiento</fullName>
            </value>
            <value>
                <fullName>Alquiler</fullName>
            </value>
            <value>
                <fullName>Alimentos</fullName>
            </value>
            <value>
                <fullName>Servicios</fullName>
            </value>
            <value>
                <fullName>Celulares</fullName>
            </value>
            <value>
                <fullName>Deudas</fullName>
            </value>
            <value>
                <fullName>Varios</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Ofrendas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gasto__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <label>Mes</label>
    <referenceTo>Mes__c</referenceTo>
    <relationshipLabel>Gastos</relationshipLabel>
    <relationshipName>Gastos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gasto__c/fields/Monto__c.field-meta.xml
<CustomField>
    <fullName>Monto__c</fullName>
    <label>Monto</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ingreso__c/Ingreso__c.object-meta.xml
<CustomObject>
    <label>Ingreso</label>
    <nameField>
        <label>Ingreso Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ingresos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ingreso__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <label>Mes</label>
    <referenceTo>Mes__c</referenceTo>
    <relationshipLabel>Ingresos</relationshipLabel>
    <relationshipName>Ingresos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ingreso__c/fields/Monto__c.field-meta.xml
<CustomField>
    <fullName>Monto__c</fullName>
    <label>Monto</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Mes__c/Mes__c.object-meta.xml
<CustomObject>
   
    <label>Mes</label>
    <nameField>
        <label>Mes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AfterUpdateIngresoTriggerHandler.cls
public with sharing class AfterUpdateIngresoTriggerHandler {

    @testVisible private Set< Id > meses;

    @testVisible private List< Mes__c > mesesWithGastosAndIngresos;
    
    @testVisible private list< Ingreso__c > newIngresos;

    @testVisible private list< Gasto__c > DiezmosToUpdate;

    public AfterUpdateIngresoTriggerHandler(list< Ingreso__c > newIngresos) 
    {
       this.newIngresos = newIngresos;
       meses = new Set< Id >();
       mesesWithGastosAndIngresos = new List< Mes__c >();
       DiezmosToUpdate = new List< Gasto__c >();

    }

    public void run() 
    {
        getAllMesesFromIngresos();
        queryMesWithDiezmoAndIngresos();
        updateUnpaidDiezmosMontos();
    }

    @testVisible
    private void getAllMesesFromIngresos() 
    {
        for( Ingreso__c ingreso : newIngresos )
        {
            meses.add( ingreso.Mes__c );
        }
    }

    @testVisible
    private void  queryMesWithDiezmoAndIngresos() 
    {
        mesesWithGastosAndIngresos = [  
                                        SELECT id, 
                                                (SELECT Monto__c, Pago__c 
                                                FROM Gastos__r 
                                                WHERE Categoria__c = 'Diezmo'
                                                LIMIT 1), 
                                                        (SELECT Monto__c 
                                                        FROM Ingresos__r)
                                        FROM Mes__c 
                                        WHERE Id 
                                        IN :meses 
                                    ];
    }

    @testVisible
    private void updateUnpaidDiezmosMontos() 
    {
        for (Mes__c mes :mesesWithGastosAndIngresos ) 
        {
           
            if( diezmoNotPaid( mes ) )
            {
                updateDiezmoMonto(mes);
            }
        }
        upsert DiezmosToUpdate;
    }

    private void updateDiezmoMonto(Mes__c mes) 
    {
        Gasto__c diezmo = mes.Gastos__r[0];
        Decimal acumulatedMonto = 0.0;

        for( Ingreso__c ingreso : mes.Ingresos__r)
        {
            acumulatedMonto += ingreso.Monto__c;
        }

        diezmo.Monto__c = acumulatedMonto * 0.1;
        DiezmosToUpdate.add( diezmo );
    }

    private boolean diezmoNotPaid( Mes__c mes ) 
    {
        if( mes.Gastos__r.size() > 0 ) 
        {
            return !mes.Gastos__r[0].Pago__c;
        }
        else return false;
       

    }
    
    
}